version: '3.8'

services:

  redis:
    image: redis
    command: redis-server --requirepass password --appendonly yes
    hostname: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0.27
    container_name: e-commerce_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: e_commerce